#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Katherine Dykes and George Scott',
 'author_email': 'systems.engineering@nrel.gov',
 'description' : 'NREL WISDEM plant cost models',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license' : 'Apache License, Version 2.0',
 'name': 'Plant_CostsSE',
 'package_data': {'Plant_CostsSE': []},
 'package_dir': {'': 'src'},
 'packages': ['nrel_csm_bos', 'test', 'nrel_csm_opex', 'ecn_offshore_opex'],
 'zip_safe': False}


setup(**kwargs)

